# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  fabricmc:
    type: maven-repository
    url: https://maven.fabricmc.net/
  quiltmc:
    type: maven-repository
    url: https://maven.quiltmc.org/repository/release/
updates:
  - package-ecosystem: "gradle"
    directory: "/main"
    registries:
      - maven-central
      - fabricmc
      - quiltmc
    schedule:
      interval: "weekly"
    allow:
      # Bundled
      - dependency-name: "org.apache.groovy:groovy*"
      - dependency-name: "net.fabricmc:mapping-io"
      - dependency-name: "com.google.auto.service:auto-service"
      - dependency-name: "dev.lukebemish.autoextension:autoextension"
      - dependency-name: "dev.lukebemish.autoextension:autoextension"
      - dependency-name: "dev.lukebemish.autoextension:autoextension"
      # Plugins
      - dependency-name: "io.github.groovymc.modsdotgroovy"
      # MDG DSL
      - dependency-name: "io.github.groovymc.modsdotgroovy:dsl"
    ignore:
      - dependency-name: "org.apache.groovy:groovy*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "/main"
    registries:
      - maven-central
      - fabricmc
      - quiltmc
    schedule:
      interval: "weekly"
    allow:
      # Plugins
      - dependency-name: "org.quiltmc.loom"
      - dependency-name: "org.quiltmc.gradle.licenser"
      - dependency-name: "io.github.p03w.machete"
      - dependency-name: "io.github.groovymc.simpleci"
      - dependency-name: "com.matthewprenger.cursegradle"
      - dependency-name: "com.modrinth.minotaur"
    commit-message:
      prefix: "[skip ci] "
