name: Release
concurrency: ci-${{ github.ref }}
on:
  - workflow_dispatch
  - push:
     branches:
       - 1.*.*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'gradle'
      - run: ./gradlew checkLicenses build
