name: Test
concurrency: ci-${{ github.ref }}
on: [workflow_dispatch, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ./main
          arguments: checkLicenses build prepareFullJar
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
      - name: Archive mod artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: main/fatjar/build/libs/groovyduvet-*-full.jar
